CREATE TABLE IF NOT EXISTS `todo` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `content` varchar(64) NOT NULL,
  `create_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

ALTER TABLE todo AUTO_INCREMENT = 1